ZDOTDIR="/home/arkuzi/.config/zsh"

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef 	# Disable CTRL-S to freez terminal.
zle_highlight=('paste:none')

# stop BEEP and auto cd
unsetopt BEEP
unsetopt autocd

# completion
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
#zstyle ':completion::complete:isof:*' menu yes select
zmodload zsh/complist
#compinit
_comp_options+=(globdots) 	# Include hidden files.

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# colors
autoload -Uz colors && colors

# useful functions
source "$ZDOTDIR/zsh-functions"

# normal files to source
zsh_add_file "zsh-exports"
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-prompt"

# plugins
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "zsh-users/zsh-autosuggestions"

# key bindings
#bindkey "^f" "fzf"

# edit line in vim with ctrl-e/v?
autoload edit-command-line; zle -N edit-command-line
